### ISSUE TITLE
How can I clean the build folder on the "cloud" ?

### ISSUE THREAD

**Issue by Bjoe** [tipi-build/community-support#3]
Hi,

For example, If I try to build a cmake based project first with `tipi -t liniux-cxx17 -u build .` and later I try to build the same project without `-u` .... then I got following error:
```
CMake Error: The source "/usr/local/share/.tipi/97fd6fb/d/redboltz/mqtt_cpp/3b1dfe2392a3eaad94ca6520d1746323fdf4ee68.b/24ba3b7/recipe/CMakeLists.txt" does not match the source "/usr/local/share/.tipi/97fd6fb/d/redboltz/mqtt_cpp/3b1dfe2392a3eaad94ca6520d1746323fdf4ee68/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
```

**Comment by daminetreg** [comment]
Hi @Bjoe,

Please apologize for the delay in our replies. We are getting back up to normal speed after MeetingCpp !

As soon as we have released the fix for the .run command ( related to #1 ) it's possible to do again :

-  `tipi -t linux-cxx17 .run " rm build/* " `

But until #1 fix is released you should look for the `/usr/local/share/.tipi/w/651d0de-mqtt_cpp.b/` hashed path build and can then delete the remote build folder with : 

```
tipi -t linux-cxx17 -vv .run "rm -r /usr/local/share/.tipi/w/651d0de-mqtt_cpp.b/"
```

What is also possibly necessariy is that you need to delete the cache.tipi.build entry in the repo Bjoe/cache.tipi.build on the releases page as in the screenshot in : https://tipi.build/documentation/10-tipi-cache#comprehensive-packs

We will provide a --purge-cache and --clean commands as we clean up the command line interface very soon.

Thanks for bearing with the rough edge of tipi at the moment !

**Comment by daminetreg** [comment]
Dear @Bjoe, this issue has finally been fixed it automatically manage the detection of reconfiguration need. 

Also ?tipi -t linux .run rm build/*` works as expected now and doesn't need the workaround anymore, it is all in the following release : https://github.com/tipi-build/cli/releases/tag/v0.0.39

Upgrade to install the new version can be done with `tipi --force-upgrade` or through the install script.
